/**
 * 页面标题唯一来源（DESIGN §3）：页头多标签页与文档标题共用。
 * 新增页面必须在此登记；未登记路由不生成标签，页头回退系统名。
 */
export const PAGE_TITLES: Record<string, string> = {
  "/": "工作台",
  "/dashboard": "工作台",
  "/dashboard/todos": "我的待办",
  "/dashboard/notifications": "我的通知",
  "/org/departments": "部门管理",
  "/org/positions": "岗位管理",
  "/access/roles": "角色管理",
  "/access/permissions": "菜单权限",
  "/access/data-scopes": "数据权限",
  "/access/audit": "权限审计",
  "/message/inbox": "站内信",
  "/message/templates": "通知模板",
  "/message/history": "发送记录",
  "/org/users": "用户管理",
  "/org/chart": "组织架构",
  "/system/services/mail": "邮件服务",
  "/system/services/storage": "对象存储",
  "/system/services/push": "消息推送",
  "/system/services/sms": "短信服务",
  "/system/services/auth": "身份认证",
  "/system/settings": "参数配置",
  "/system/dictionaries": "字典管理",
  "/system/jobs": "定时任务",
  "/system/announcements": "公告管理",
  "/system/about": "关于系统",
  "/approval/todo": "我的待办",
  "/approval/mine": "我发起的",
  "/approval/cc": "抄送我的",
  "/approval/templates": "审批模板",
  "/approval/flows": "审批流程",
  "/audit/operations": "操作日志",
  "/audit/changes": "数据变更",
  "/audit/logins": "登录日志",
  "/audit/compliance": "合规报告",
  "/sync/sources": "数据源配置",
  "/sync/tasks": "同步任务",
  "/sync/runs": "执行记录",
  "/sync/schedules": "调度管理",
  "/report/builtin": "预置报表",
  "/report/custom": "自定义报表",
  "/report/subscriptions": "报表订阅",
  "/report/exports": "数据导出",
  "/integration/api-keys": "API 密钥",
  "/integration/webhooks": "Webhook",
  "/integration/logs": "调用日志",
  "/integration/docs": "接口文档",
  "/settings/profile": "个人中心",
};
