#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.

TOTAL_STAGES=6

banner "Supabase staging 上云向导（admin 项目）"

# ── 1. 创建 staging 项目 ──────────────────────────────────────────────────
stage "创建 staging 项目"
say "在 Supabase 创建一个新项目作为 staging 环境（与 prod 隔离）。"
open_url "https://supabase.com/dashboard/new"
step "选择组织（与 prod 同 org 便于管理）。"
step "项目名建议：admin-staging（或 plm-staging）。"
step "数据库密码：生成并保存到密码管理器（后续不需要，但备份需要）。"
step "区域：与 prod 一致（降低行为差异）。"
note "创建约 2 分钟。创建好后进入项目首页。"
pause "项目创建完成后再继续"

# ── 2. 采集 staging 连接信息 ─────────────────────────────────────────────
stage "采集 staging 连接信息"
say "从 staging 项目的 API 设置页采集 URL 与密钥。"
open_url "https://supabase.com/dashboard/project/_/settings/api"
step "左上角切换到你的 staging 项目。"
step "复制 Project URL（形如 https://xxxx.supabase.co）。"
ask STAGING_SUPABASE_URL "粘贴 Project URL："
step "复制 anon public key。"
ask STAGING_SUPABASE_ANON_KEY "粘贴 anon key："
step "复制 service_role key（点击 Reveal）。"
ask_secret STAGING_SUPABASE_SERVICE_ROLE_KEY "粘贴 service_role key："
ENV_FILE=.env.staging write_env NEXT_PUBLIC_SUPABASE_URL "$STAGING_SUPABASE_URL"
ENV_FILE=.env.staging write_env NEXT_PUBLIC_SUPABASE_ANON_KEY "$STAGING_SUPABASE_ANON_KEY"
ENV_FILE=.env.staging write_env SUPABASE_SERVICE_ROLE_KEY "$STAGING_SUPABASE_SERVICE_ROLE_KEY"
note "已写入 .env.staging（本地验证用，不提交 git）。"

# ── 3. 关联并推送迁移 ────────────────────────────────────────────────────
stage "关联 staging 并推送 121 条迁移"
say "把本地仓库关联到 staging 项目，然后推送全部迁移。"
REF=$(echo "$STAGING_SUPABASE_URL" | sed -E 's|https://([^.]+)\.supabase\.co.*|\1|')
note "解析到项目 ref：$REF"
say "执行（需要数据库密码，即第 1 步保存的密码）："
step "supabase link --project-ref $REF"
step "supabase db push --include-all"
note "推送 121 条迁移约 3-8 分钟。若报密码错误：Dashboard → Settings → Database → Reset password。"
warn "推送前请确认：本地栈数据不会上传（只推结构；seed 仅 db reset 时用）。"
confirm "迁移推送成功（Applied 121 migrations）？" || warn "推送失败，请先解决再继续；可重新运行本向导。"

# ── 4. 推送 seed 测试数据（可选）─────────────────────────────────────────
stage "推送 seed 测试账号（可选）"
say "staging 默认无 seed（db push 不跑 seed）。如需 5 个测试账号："
if confirm "要在 staging 创建测试账号（admin/engineer/planner/buyer/quality@example.com）？"
then
  step "执行：supabase db reset --linked（会重建 staging 库并重放迁移+seed）"
  warn "注意：db reset --linked 会清空 staging 现有数据（当前为空，安全）。"
  pause "完成后再继续"
else
  note "跳过：可后续用 Dashboard → Authentication → Add user 手动创建 admin。"
fi

# ── 5. 本地验证 staging ──────────────────────────────────────────────────
stage "本地验证 staging 环境"
say "用 .env.staging 起 dev server 验证关键路径。"
step "执行：cp .env.local .env.local.bak && cp .env.staging .env.local"
step "执行：npm run dev -- -p 3000 -H 0.0.0.0"
step "浏览器打开 http://192.168.10.213:3000，登录 admin@example.com / admin123。"
say "验证清单："
step "工作台统计卡片有数字（非报错）。"
step "用户管理列表可见 5 个账号；编辑 Sheet 部门/岗位下拉正常。"
step "审批中心发起 demo 审批 → 待办出现 → 通过。"
step "审计中心操作日志有上述操作记录。"
confirm "staging 验证通过？" || warn "有问题先修复再继续；本地 .env.local.bak 可恢复。"

# ── 6. 恢复本地环境 + 上线 prod 准备 ────────────────────────────────────
stage "恢复本地环境并准备 prod"
step "执行：cp .env.local.bak .env.local（恢复本地栈开发环境）。"
say "staging 验证通过后，prod 推送步骤："
step "备份 prod：Dashboard → Settings → Backups（确认有最近备份）。"
step "关联 prod：supabase link --project-ref mnhtuekkxiqsseoesjfn"
step "推送：supabase db push --include-all"
step "重生成类型：npm run db:types"
step "部署平台配置 SUPABASE_SERVICE_ROLE_KEY（ban 功能需要）。"
note "prod 推送建议低峰期执行；失败可回滚备份。"
confirm "已记录 prod 步骤？" && note "向导完成。"

finish
